### ISSUE TITLE
Can't get result from function

### ISSUE THREAD

**Issue by creativefull** [bulentv/js_zklib#1]
hi bulentv, i'm using your module, i want to ask why i can't result from callback with all function in this module

this is mycode
```
var ZK = new ZKLib({
	ip : '192.168.1.202',
	port : 4370,
	// inport: 5200
});

ZK.connect((err, ret) => {
	console.log("connected");
	ZK.serialNumber(function(err, t) {
		console.log(err, t);
	})
})
```

and i just get result
```
connected
```

i'm nothing get result from <code>serialNumber()</code> .
thnks for help me :)

**Comment by bulentv** [comment]
@creativefull,

Could you pull / checkout the [dev](https://github.com/bulentv/js_zklib/tree/dev) branch to get some more info about the comms?
There should be cmd: and reply: lines out to stdout and let me see those information to work on the issue.

**Comment by creativefull** [comment]
it works , just uncomment
// inport: 5200

thnks
