### ISSUE TITLE
Enable repo in travis-ci / Include npm publish in travis-ci on new tag

### ISSUE THREAD

**Issue by mribichich** [bulentv/js_zklib#27]
@bulentv whenever you can could you please enable the repo in travis-ci

I've already added the `yml` file. All you have to do is enable it

thanks

**Comment by mribichich** [comment]
Hi @bulentv , were you able to see this? thanks

**Comment by mribichich** [comment]
great thanks, I can see you already did it!
Closing it. 

If you are ok with it, we could add the npm publish command on every new `tag/release`.
That way you dont have to do it your self manually. And since it's in your user, you only have access to token variables

**Comment by bulentv** [comment]
Yes I've enabled the repo in travis-ci but since I'm familiar with travis I wasn't sure everything was properly set. It is a good idea to have a auto npm publish of course. I will take a look.

**Comment by mribichich** [comment]
great! I'll add the npm section on the travis-ci file, and you would have to add the NPM_PRIVATE_TOKEN to the secret variables in the project under you account, since only you have access

**Comment by mribichich** [comment]
Here are the [docs](https://docs.travis-ci.com/user/deployment/npm/)

**Comment by bulentv** [comment]
Pushed the changes on .travis.yml, haven't tested it tough.

**Comment by mribichich** [comment]
great, the build passes. So the rest is ok. 

I could try it pushing a new tag v0.2.2

**Comment by mribichich** [comment]
I fixed the script and now its working. v0.2.3 in npm now
thanks!
