### ISSUE TITLE
Wrong state value?

### ISSUE THREAD

**Issue by Adhik** [bulentv/js_zklib#29]
Hi,

Thank you for your nice work here.
I tried js_zklib with Solution X100-c attendance machine which is working fine (Firmware ver 7.0.3.104 - 20160519). 

However, it looks like `getAttendance()` always returned the same value for attendance log's state, which is always **1** (checked out?), no matter which state button that I used on the machine (check out, check in, overtime, etc). 

Manual view on the attendance machine showed correct state (status): 0 for check in and 1 for check out.

I tried https://github.com/dnaextrim/php_zklib, but it looks it has similar bug as well (attendance status row always "1" as well).

Using `v6.60` or `legacy` for `attendanceParser` option gave the same result as well.

Could it be that the parsing will be different for this firmware?

**Comment by Adhik** [comment]
ok, I got it. 

After some debugging on **att_parser_v6.60.js**: it looks like `attdata[33]` holds the correct value for the log's state.

![attdata](https://user-images.githubusercontent.com/8499271/40270432-f77c3eb6-5bbf-11e8-87a7-18d49f96b401.png)

In my case, it showed the same state's value from a manual view on the machine, which were:
0 -> check-out
1 -> check-in
4 -> overtime-in
5 -> overtime-out

Maybe you can consider this for a new parser for v7 firmware.
Cheers!

**Comment by mribichich** [comment]
Let me check this right now please if its the same with my firmware, because I wasn't using the state column

**Comment by mribichich** [comment]
This is ready and fixed. I guess will have a new release tomorrow
