### ISSUE TITLE
Always show uid is 0

### ISSUE THREAD

**Issue by creativefull** [bulentv/js_zklib#3]
hi :) sorry i've problem again , 
i try to get attendance with function ```getattendance()``` i'm successful get result, but always show uid is 0

i'm try run ZKLib in php and i never get 0 uid of 

this is when i run ZKLib php
![screenshot_35](https://cloud.githubusercontent.com/assets/13174684/18225153/6a99e2f8-7216-11e6-92cd-6525e85b3acd.png)

run in nodejs
![screenshot_36](https://cloud.githubusercontent.com/assets/13174684/18225161/a53dfdae-7216-11e6-807c-e92ffbff1bde.png)

ok thanks

**Comment by bulentv** [comment]
@creativefull,

Could you pull / checkout the [dev](https://github.com/bulentv/js_zklib/tree/dev) branch to get some more info about the comms?
There should be cmd: and reply: lines out to stdout and let me see those information to work on the issue.

**Comment by creativefull** [comment]
i'm already fix it,. thanks
