### ISSUE TITLE
Any idea on how to support ADMS/WDMS/push?

### ISSUE THREAD

**Issue by luixal** [bulentv/js_zklib#33]
**DISCLAIMER**: I know this project is not intended to support that, but I've gone crazy looking for it.

Does anyone know about a node package, OSS with a rest api or similar to handle data from ZK devices through ADMS/push system?

Thanks and cheers for the great work on this package! :)

**Comment by mribichich** [comment]
On my side, I dont know of any. I don't even know what's ADMS/push, sorry

**Comment by luixal** [comment]
Some of the iClock readers (not sure which models/firmware versions) don't need you to have a direct network connection to them, they send http GET/POST queries to gather configuration options (or commands) / send info to the server.

This is great because having an UDP connection to a remote reader is king of weird sometimes (imagine an iClock outside your network, in a different office).

I've written a simple nodejs + express script to get this http queries and I'm getting them, but I can't find where the info is stored :(

My idea was to use the parsers in this project to handle them, but I can't locale where the info comes.

I'll close this issue as it's not really related to this project.

**Comment by karthikeyan5** [comment]
@luixal, 
I have been on a similar quest too... 
have you had any luck with capturing the "push to ADMS" data from the biometric device? 
Thanks

**Comment by luixal** [comment]
Hi @karthikeyan5 I finally got in touch with ZK and they have documentation on the protocol (basically you have to develop an HTTP server that listens/answers devices queries). Thing is, that documentation is heavily protected through NDA and that stuff so it's makes legally impossible to publish OSS that handles those requests :(

They also offer the WMDS software, written in python that is basically an implementation of that HTTP server (with some limitations as it's too simple for many cases).

**Comment by sebvif** [comment]
hi. i came across this post while looking for adms integration. i found a document that explains what the device is constantly sending to the configured server. this is the link 
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjj7Y_bmIHoAhXwk60KHVWRBC8QFjAAegQIARAB&url=http%3A%2F%2Ff02.s.alicdn.com%2Fkf%2FHTB1PANmFVXXXXaCXVXX.PRXFXXXk.pdf&usg=AOvVaw0ZIW1aoooWpc6yXFPHqAI5
with that and some packet captures i've been able to make some progress. 
there is also this. i used google translate ;)
https://docs.nufaza.com/docs/devices/zkteco_attendance/push_protocol/

**Comment by fersrc** [comment]
Hi. I have a little issue with three different devices. Let me explain, in the Horus and Proface I get Biodata from the device when I register a face on them, also I can send them the info, But i have a 100TC that send me FACE data in 12 parts (FID=0 to FID=11)
also if i try DATA QUERY BIODATA *  command the 100TC send me a -3 (Insufficient caching required) return value. 
Does anyone know how can I send the Biodata I got from Horus/Proface to 100TC? 

ps. user and pics cand be send without problem

**Comment by mValencia123** [comment]
Hi! I have a issue when the clock connects to my server. When I configure the wifi in the clock, it gets date and time from internet. But when I configure the ADMS server in the clock it changes the time adding 14 hours to actual time. 

Example: If now is 08:00 am, clock changes time to 10:00 pm.

Anyone can help me how to solve it?
