### ISSUE TITLE
Support for TCP socket connections

### ISSUE THREAD

**Issue by mribichich** [bulentv/js_zklib#35]
@bulentv I'm have to support TCP sockets also.

So I'm planning on doing some improvements and cleanup to be able to do it without touching the core.

I thought one could configure to use one or the other. The default would be UDP like now. Nothing would change on the public api.

The idea would be to create the socket according to the config, and leave everything else the same.

The only difference between the two is UDP listens for the `message` event and TCP for the `data` event.

The rest is almost the same. All the decoding and encoding is the same.

Wanted to let you know, maybe we could release a v3.x, but since the public api is not changing, we could treat it like a new feature and not a breaking change

let you know when I have it done and test it

thanks

**Comment by bulentv** [comment]
@mribichich 

Sorry for not being able to come back here often enough these days. 
I'm glad that you are doing it very well. You are welcome to make additions and your plan sounds OK to me.

I agree with you that if implementing TCP sockets will not cause any public API change, we can keep v2.x.

Thanks

**Comment by mribichich** [comment]
great thanks! I let you know when its done

**Comment by mribichich** [comment]
done!
