### ISSUE TITLE
GetAttendance function with different results

### ISSUE THREAD

**Issue by mribichich** [bulentv/js_zklib#8]
Hi there. I've been trying to use your library, but it seems that I may have a different version of zkaccess, because the GetAttendace message is not being parse correctly

In line [19](https://github.com/bulentv/js_zklib/blob/241bdd17eee66b35d81465a46a0fd93e4de2df0d/zklib/zkattendance.js#L19) you have:

``` javascript
    var att = {
      uid: parseInt(attdata.slice(0,4).toString("ascii").split('\0').shift()) || 0,
      id: parseInt(attdata.slice(4,8).toString("ascii").split('\0').shift()) || 0,
      state: attdata[28],
      timestamp: self.decode_time(attdata.readUInt32LE(29))
    };
    return att;
```

But the uid and id are empty or wrong.

This is the buffer that comes:

- 00 00 1a 01 34 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 58 0d 04 23 01
- 00 00 0d 01 31 33 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0f 5d 24 03 23 01 00 00 00 00 00 00

I had to change it to this in order to work:

``` javascript
    var att = {
      id: (attdata[3] << 8) + attdata[2],
      userId: parseInt(attdata.slice(4, 6).toString("ascii")),
      state: attdata[28],
      timestamp: self.decode_time(attdata.readUInt32LE(29)),
    };
```

I would love to PR back to the lib, but is it working for you? How could we make it compatible with your version of the protocol and mine.

The version command returns 10

thanks!

**Comment by mribichich** [comment]
device firmware v6.60 Aug 10 2015

**Comment by mribichich** [comment]
@bulentv what do you think about this? I was thinking that maybe we could solve it with two options:

- On one side allow the user to specify a `parsing` function in `getattendances` to be use instead of the default one (which is the one its there right now). The func would be optional of course

The drawback from this one is that the decode func I have to use will not be in the lib, so others cannot use it

``` javascript
ZKLib.prototype.getattendance = function(decodingFunc, cb) {
```

- The other option would be to add another decode func like the one I need for my protocol version, and allow the user to choose one. Dont know exactly how, maybe passing an option in the new ZK(options...) specifying the decode function

what do you think?

thanks

**Comment by bulentv** [comment]
@mribichich 

I definetely prefer the second option. If you can implement your decoder in some file, named like att_parser_v6.60.js so we can import and refer it in the config. I will in the meantime move the existing parser to a separate file called att_parser_legacy.js.

One issue is unfortunately I no longer have access to any device to test the code. Hope we will have some feedback.

Please continue using ES2015 styling, I'm converting the other files as well.

Thanks

**Comment by mribichich** [comment]
Ok great, I like it better too. 

I of course have access to the one I'm using but only that one.

I'll let you know when its ready.

thanks

**Comment by mribichich** [comment]
I can extract both if you want

**Comment by bulentv** [comment]
Yes, it would be great. I haven't had time to do it, completed the es2015 transition though.
